### ISSUE TITLE
createSaveEvidence函数的覆盖实现问题

### ISSUE THREAD

**Issue by shiqinfeng1** [six-days/ethereum-contracts#1]
https://github.com/six-days/ethereum-contracts/blob/ff01c51d4382d0fb24474844a5d2d5135b1c8ac9/evidence/EvidenceVoteSaveHandler.sol#L48

createSaveEvidence函数在base合约和继承合约中都有定义，这里调用的时候，应该会调用继承合约中的createSaveEvidence函数。但实际上应该思想调用基础合约中的createSaveEvidence函数吧？

所以，createSaveEvidence函数不应该是覆盖吧？

**Comment by six-days** [comment]
之所以EvidenceVoteSaveHandler合约要覆盖EvidenceBaseSaveHandler合约中的createSaveEvidence方法，是要避免跳过投票而直接上链的情况。
投票上链的存证，只有在投票数满足阈值后，调用saveEvidenceToChain方法才能上链。这个方法不能调用createSaveEvidence方法，已修复。
